fix: add python version determination (#130)
* fix: add python version determination

* fix: step naming

Co-authored-by: Lukas Thaler <113890185+lukasthalerINNIO@users.noreply.github.com>

* fix: step naming

* fix: remove duplicated steps

---------

Co-authored-by: Lukas Thaler <113890185+lukasthalerINNIO@users.noreply.github.com>

diff --git a/workflow-templates/python-dependency-check.yml b/workflow-templates/python-dependency-check.yml
--- a/workflow-templates/python-dependency-check.yml
+++ b/workflow-templates/python-dependency-check.yml
@@ -20,13 +20,49 @@ on:
   workflow_dispatch:
 
 jobs:
+  setup:
+    name: 'Job: Python setup'
+    outputs:
+    pythonVersionFile: ${{steps.set_outputs.outputs.pythonVersionFile}}
+
+    steps:
+      - name: Check python version determination (pyproject.toml)
+        id: check_file_pyproject
+        uses: andstor/file-existence-action@v3
+        with:
+          fail: false
+          files: 'pyproject.toml'
+
+      - name: Use pyproject.toml as python version file
+        if: steps.check_file_pyproject.outputs.files_exists == 'true'
+        run: echo PYTHON_VERSION_FILE="pyproject.toml" >> ${GITHUB_ENV}
+
+      - name: Check python version determination (.python-version)
+        if: steps.check_file_pyproject.outputs.files_exists == 'false'
+        id: check_file_python_version
+        uses: andstor/file-existence-action@v3
+        with:
+          fail: false
+          files: '.python-version'
+
+      - name: Use .python-version as python version file
+        if: steps.check_file_python_version.outputs.files_exists == 'true'
+        run: echo PYTHON_VERSION_FILE=".python-version" >> ${GITHUB_ENV}
+
+      - name: Check python version determination
+        if: steps.check_file_pyproject.outputs.files_exists == 'false' &&  steps.check_file_python_version.outputs.files_exists == 'false'
+        run: |
+          echo "::error Either pyproject.toml or .python-version must exists (and contain a python version number)"
+          exit 1
+
+      - id: set_outputs
+        name: Set python version file
+        run: echo "::set-output name=pythonVersionFile::${{ env.PYTHON_VERSION_FILE}}"
+
   dependencyCheck:
     name: 'Job: Dependency check'
+    needs: ['setup']
     runs-on: [self-hosted-standard]
-
-    strategy:
-      matrix:
-        python-version: ['3.10']
 
     steps:
       - name: Set git to use LF
@@ -114,19 +150,19 @@ jobs:
           fail: false
           files: 'poetry.lock'
 
-      - name: Prepare python ${{ matrix.python-version }} (with pip)
+      - name: Prepare python (with pip)
         if: steps.check_poetry.outputs.files_exists == 'false'
         uses: actions/setup-python@v5
         with:
           cache: 'pip'
-          python-version: ${{ matrix.python-version }}
+          python-version-file: ${{fromJSON(needs.setup.outputs.pythonVersionFile)}}
 
-      - name: Prepare python ${{ matrix.python-version }} (with poetry)
+      - name: Prepare python (with poetry)
         if: steps.check_poetry.outputs.files_exists == 'true'
         uses: actions/setup-python@v5
         with:
           cache: 'poetry'
-          python-version: ${{ matrix.python-version }}
+          python-version-file: ${{fromJSON(needs.setup.outputs.pythonVersionFile)}}
 
       - name: Check poetry file existence
         uses: andstor/file-existence-action@v3
