fix: naming issues

diff --git a/workflow-templates/python-deploy.yml b/workflow-templates/python-deploy.yml
--- a/workflow-templates/python-deploy.yml
+++ b/workflow-templates/python-deploy.yml
@@ -20,65 +20,7 @@ jobs:
     name: 'Job: Python setup'
     runs-on: [self-hosted-standard]
     outputs:
-      pythonVersionFile: ${{steps.set_outputs.outputs.pythonVersionFile}}
-
-    steps:
-      - name: Set git to use LF
-        run: |
-          git config --global core.autocrlf false
-          git config --global core.eol lf
-
-      - name: Checkout git repository
-        uses: actions/checkout@v4
-        with:
-          sparse-checkout: .
-
-      - name: Check python version determination (pyproject.toml)
-        id: check_file_pyproject
-        uses: andstor/file-existence-action@v3
-        with:
-          fail: false
-          files: 'pyproject.toml'
-
-      - name: Use pyproject.toml as python version file
-        if: steps.check_file_pyproject.outputs.files_exists == 'true'
-        run: echo PYTHON_VERSION_FILE="pyproject.toml" >> ${GITHUB_ENV}
-
-      - name: Check python version determination (.python-version)
-        if: steps.check_file_pyproject.outputs.files_exists == 'false'
-        id: check_file_python_version
-        uses: andstor/file-existence-action@v3
-        with:
-          fail: false
-          files: '.python-version'
-
-      - name: Use .python-version as python version file
-        if: steps.check_file_python_version.outputs.files_exists == 'true'
-        run: echo PYTHON_VERSION_FILE=".python-version" >> ${GITHUB_ENV}
-
-      - name: Check python version determination
-        if: steps.check_file_pyproject.outputs.files_exists == 'false' &&  steps.check_file_python_version.outputs.files_exists == 'false'
-        run: |
-          echo "::error Either pyproject.toml or .python-version must exists (and contain a python version number)"
-          exit 1
-
-      - id: set_outputs
-        name: Set python version file
-        run: echo pythonVersionFile="${{ env.PYTHON_VERSION_FILE}}" >> ${GITHUB_OUTPUT}
-
-  buildAndDeploy:
-    name: 'Job: Build and deploy'
-    needs: ['setup']
-    runs-on: [self-hosted-standard]
-    concurrency:
-      group: deploy_${{ github.ref }}
-      cancel-in-progress: false
-    outputs:
-      component-name: ${{ env.COMPONENT_NAME }}
-      deploy-environment: ${{ env.DEPLOY_ENVIRONMENT }}
-      docker-identifier: ${{ env.DOCKER_IDENTIFIER }}
-      helm-value-file: ${{ env.HELM_VALUE_FILE }}
-      tag: ${{ env.TAG }}
+      python-version-file: ${{steps.set_outputs.outputs.pythonVersionFile}}
 
     steps:
       - name: Set git to use LF
@@ -91,12 +33,6 @@ jobs:
         with:
           # Disabling shallow clone is recommended for improving relevancy of reporting
           fetch-depth: 0
-
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_READONLY_PAT }}
 
       - name: Check workflow config file existence
         uses: andstor/file-existence-action@v3
@@ -212,6 +148,65 @@ jobs:
       - name: Set env 'DEPLOY_TARGETS' for master branch (only run build task; never deploy)
         if: env.BRANCH_NAME == 'master'
         run: echo DEPLOY_TARGETS="none" >> ${GITHUB_ENV}
+
+      - name: Check python version determination (pyproject.toml)
+        id: check_file_pyproject
+        uses: andstor/file-existence-action@v3
+        with:
+          fail: false
+          files: 'pyproject.toml'
+
+      - name: Use pyproject.toml as python version file
+        if: steps.check_file_pyproject.outputs.files_exists == 'true'
+        run: echo PYTHON_VERSION_FILE="pyproject.toml" >> ${GITHUB_ENV}
+
+      - name: Check python version determination (.python-version)
+        if: steps.check_file_pyproject.outputs.files_exists == 'false'
+        id: check_file_python_version
+        uses: andstor/file-existence-action@v3
+        with:
+          fail: false
+          files: '.python-version'
+
+      - name: Use .python-version as python version file
+        if: steps.check_file_python_version.outputs.files_exists == 'true'
+        run: echo PYTHON_VERSION_FILE=".python-version" >> ${GITHUB_ENV}
+
+      - name: Check python version determination
+        if: steps.check_file_pyproject.outputs.files_exists == 'false' &&  steps.check_file_python_version.outputs.files_exists == 'false'
+        run: |
+          echo "::error Either pyproject.toml or .python-version must exists (and contain a python version number)"
+          exit 1
+
+      - id: set_outputs
+        name: Set python version file
+        run: echo pythonVersionFile="${{ env.PYTHON_VERSION_FILE}}" >> ${GITHUB_OUTPUT}
+
+  build:
+    name: 'Job: Build'
+    needs: ['setup']
+    runs-on: [self-hosted-standard]
+    concurrency:
+      group: deploy_${{ github.ref }}
+      cancel-in-progress: false
+
+    steps:
+      - name: Set git to use LF
+        run: |
+          git config --global core.autocrlf false
+          git config --global core.eol lf
+
+      - name: Checkout git repository
+        uses: actions/checkout@v4
+        with:
+          # Disabling shallow clone is recommended for improving relevancy of reporting
+          fetch-depth: 0
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_READONLY_PAT }}
 
       - name: Initialize 'RETAG'
         run: echo RETAG=false >> ${GITHUB_ENV}
@@ -513,37 +508,13 @@ jobs:
             "component_name": "${{ env.COMPONENT_NAME }}",
             "deployment_files": ${{ env.DEPLOY_TARGETS }}}'
 
-      - name: Merging release changes to master
-        if: env.IS_RELEASE == 'true' && github.event.release.target_commitish != 'develop'
-        uses: peter-evans/repository-dispatch@v3
-        with:
-          token: ${{ secrets.CI_PAT }}
-          event-type: merge
-          client-payload: '{
-            "commitish": "${{ github.event.release.target_commitish }}",
-            "source_branch": "${{ env.BRANCH_NAME }}",
-            "target_branch": "master",
-            "tag": "${{ env.TAG }}"}'
-
-      # target_commitish can be "develop" for releases that are solely based on tags
-      - name: Merging release changes to master (not using develop commitish, but tag ref)
-        if: env.IS_RELEASE == 'true' && github.event.release.target_commitish == 'develop'
-        uses: peter-evans/repository-dispatch@v3
-        with:
-          token: ${{ secrets.CI_PAT }}
-          event-type: merge
-          client-payload: '{
-            "source_branch": "${{ env.BRANCH_NAME }}",
-            "target_branch": "master",
-            "tag": "${{ env.TAG }}"}'
-
-  helmDeploy:
-    if: ${{ needs.buildAndDeploy.outputs.helm-value-file != 'none' && needs.buildAndDeploy.outputs.deploy-environment != 'none' }}
-    name: 'Job: Deploy (with a helm value file)'
-    needs: ['buildAndDeploy']
+  deployHelm:
+    name: 'Job: Deploy'
+    if: needs.setup.outputs.deployment-method == 'helm'
+    needs: ['setup', 'build']
     runs-on: [self-hosted-standard]
     concurrency:
-      group: 'helmDeploy_${{ github.ref }}'
+      group: 'deployHelm_${{ github.ref }}'
       cancel-in-progress: false
 
     steps:
@@ -578,20 +549,20 @@ jobs:
 
       - name: Fetch value file contents
         if: env.VERBOSE_LOGGING == 'true'
-        run: cat deployment-repo/${{ needs.buildAndDeploy.outputs.deploy-environment }}/${{ needs.buildAndDeploy.outputs.helm-value-file }}
+        run: cat deployment-repo/${{ matrix.deploy-target }}
 
       - name: Determine value file to change
         id: helm-value-file
-        run: echo filename='deployment-repo/${{ needs.buildAndDeploy.outputs.deploy-environment }}/${{ needs.buildAndDeploy.outputs.helm-value-file }}' >> ${GITHUB_OUTPUT}
+        run: echo filename='deployment-repo/${{ matrix.deploy-target }}' >> ${GITHUB_OUTPUT}
 
       - name: Update component image tag for Deployment and Rollout
         uses: mikefarah/yq@v4
         with:
-          cmd: yq -i '.image.tag = "${{ needs.buildAndDeploy.outputs.docker-identifier }}"' ${{ steps.helm-value-file.outputs.filename }}
+          cmd: yq -i '.image.tag = "${{ needs.setup.outputs.docker-identifier }}"' ${{ steps.helm-value-file.outputs.filename }}
 
       - name: Fetch updated value file contents
         if: env.VERBOSE_LOGGING == 'true'
-        run: cat deployment-repo/${{ needs.buildAndDeploy.outputs.deploy-environment }}/${{ needs.buildAndDeploy.outputs.helm-value-file }}
+        run: cat deployment-repo/${{ matrix.deploy-target }}
 
       - name: Commit changed value file (to deployment repo)
         env:
@@ -600,17 +571,37 @@ jobs:
           cd deployment-repo
           git config --global user.email "myplant-io-automation@innio.com"
           git config --global user.name "myplant-io-automation"
-          git add ${{ needs.buildAndDeploy.outputs.deploy-environment }}/${{ needs.buildAndDeploy.outputs.helm-value-file }}
-          git commit --allow-empty -m "chore(release): use ${{ needs.buildAndDeploy.outputs.docker-identifier }} on ${{ needs.buildAndDeploy.outputs.deploy-environment }}"
+          git add ${{ matrix.deploy-target }}
+          git commit --allow-empty -m "chore(release): use ${{ needs.setup.outputs.docker-identifier }}"
           git push
 
-      # - name: Update value file
-      #   run: |
-      #     IFS=';' read -ra targets <<< "$DEPLOY_TARGETS"
-      #     cd deployment-repo
-      #     git config --global user.email "myplant-io-automation@innio.com"
-      #     git config --global user.name "myplant-io-automation"
-      #     for target in ${targets[@]}; do sed -i -r "s/([\t ]+image: (('|\")?)${DOCKER_REGISTRY}\/${DOCKER_REPOSITORY}:${DOCKER_TAG_PREFIX}).*/\1${VERSION}\2/g" $target; git add $target; done
-      #     echo nr_files_changed=$(git status --porcelain | wc -l) >> ${GITHUB_OUTPUT}
-      #     git commit --allow-empty -m "chore(release): ${{ needs.buildAndDeploy.outputs.docker-identifier }}"
-      #     git push
+  releaseMerging:
+    name: "Job: Merging release changes"
+    if: always() && needs.build.outputs.is-release == 'true'
+    needs: ['build', 'deployLegacy', 'deployHelm']
+    runs-on: [self-hosted-standard]
+
+    steps:
+      - name: Merging release changes to master
+        if: env.IS_RELEASE == 'true' && github.event.release.target_commitish != 'develop'
+        uses: peter-evans/repository-dispatch@v3
+        with:
+          token: ${{ secrets.CI_PAT }}
+          event-type: merge
+          client-payload: '{
+            "commitish": "${{ github.event.release.target_commitish }}",
+            "source_branch": "${{ env.BRANCH_NAME }}",
+            "target_branch": "master",
+            "tag": "${{ env.TAG }}"}'
+
+      # target_commitish can be "develop" for releases that are solely based on tags
+      - name: Merging release changes to master (not using develop commitish, but tag ref)
+        if: env.IS_RELEASE == 'true' && github.event.release.target_commitish == 'develop'
+        uses: peter-evans/repository-dispatch@v3
+        with:
+          token: ${{ secrets.CI_PAT }}
+          event-type: merge
+          client-payload: '{
+            "source_branch": "${{ env.BRANCH_NAME }}",
+            "target_branch": "master",
+            "tag": "${{ env.TAG }}"}'
